---
name: Debug
on:
  push:
  pull_request:
  page_build:
env:
  QT_DEBUG_PLUGINS: 1
  CMAKE_PREFIX_PATH: $HOME/Qt/5.12.5/clang_64
jobs:
  build:
    runs-on: macos
    steps:
      - uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.2.0
        timeout-minutes: 10
        with:
          version: 5.12.5
          target: desktop
          host: ${{ matrix.env.qtplatform }}
          install-deps: true
          modules: qtwebengine qtnetworkauth qtwebglplugin qtscript debug_info
      - name: Variables
        run: |
          echo CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH
          echo HOME: $HOME
          echo "ninja version: $(ninja --version)"
          git --version
          qmake --version
          cmake --version
          echo $PATH
          echo $QT_PLUGIN_PATH
          echo $QT_DEBUG_PLUGINS
      - name: Print
        run: |
          pwd
          ls -la
          cd ../
          pwd
          ls -la
          cd $HOME/Qt/5.12.5/clang_64
          ls -la
...