---
name: Debug
on:
  push:
  pull_request:
  page_build:
env:
  QT_DEBUG_PLUGINS: 1
jobs:
  build:
    runs-on: macos
    steps:
      - uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.2.0
        timeout-minutes: 10
        with:
          version: 5.12.5
          target: desktop
          host: ${{ matrix.env.qtplatform }}
          install-deps: true
          modules: qtwebengine qtnetworkauth qtwebglplugin qtscript debug_info
      - name: Variables
        run: |
        echo CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH
      - name: Print
        run: |
          pwd
          ls -la
          cd ../
          pwd
          ls -la
...